version: "3.9"

services:
  nextapp:
    container_name: ae-solar
    image: ae-solar
    build: .
    networks:
      - aesolar_network
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - pgadmin
    volumes:
      - ./html:/var/www/html
      - /home/aesolar/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/aesolar/config/nginx/httpd-cert:/var/www/httpd-cert
    networks:
      - aesolar_network

# volumes:
#   postgres_data:
#   pgadmin_data:

networks:
  aesolar_network:
    external: true
