version: "3.9"

services:
  nextapp:
    container_name: ae-solar
    image: ae-solar
    build: .
    networks:
      - aesolar_network
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - pgadmin
    volumes:
      - ./html:/var/www/html
      - /home/aesolar/docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aesolar_network

# volumes:
#   postgres_data:
#   pgadmin_data:

networks:
  aesolar_network:
    name: strapi_network
    external: true
