import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/app/components/Navigation";
import Footer from "@/app/components/Footer";
import localFont from "next/font/local";

// const criteriacf = localFont({
//   src: [
//     {
//       path: "./fonts/criteriacf-demibold.otf",
//       weight: "800",
//       style: "normal",
//     },
//     {
//       path: "./fonts/criteriacf-medium.otf",
//       weight: "600",
//       style: "normal",
//     },
//   ],
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1320px] my-0 mx-auto">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
