import { BlogPosts } from "@/app/[locale]/company/news/types";

export const BLOG_READ_THOUGHTS = "Lesen Sie Über Uns.";
export const BLOG_ON_THE_BLOG = "In den Medien.";
export const BLOG_MOST_POPULAR = "Am Beliebtesten";
export const BLOG_RECENT_POSTS = "Neueste Beiträge.";
export const BLOG_POSTS_PER_PAGE = 7;

export const BLOG_POSTS: BlogPosts[] = [
  {
    id: 1,
    type: "explainer",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    type: "tips",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    type: "Exhibition",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    type: "explainer",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    type: "explainer",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 6,
    type: "explainer",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 7,
    type: "explainer",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
  {
    id: 8,
    type: "explainer",
    typeNumber: "000",
    title: "How do grid-connected PV systems save your bills?",
    statistics: {
      creationDate: "2024, 25 Jan",
      readingTime: "5 mins",
      author: "JJ NI",
    },
    content: [
      {
        sectionHeadline: "General Infomation",
        block: [
          {
            paragraphs: [
              "As the demand for sustainable and cost-effective energy solutions continues to grow, grid-connected photovoltaic (PV) systems have emerged as a prominent option for both residential and commercial applications. Grid-tied systems are connected to the grid and can interact with it to sell excess power back to the utility company or draw power from the grid when needed. This article aims to provide a comprehensive understanding of the process involved in generating electricity from grid-tied PV systems.",
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
          {
            subtitle: "1. Solar Energy Conversion",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "The generated DC electricity is then fed into an inverter, where it is converted into alternating current (AC) electricity. This conversion is essential as most electrical appliances and the grid itself operate on AC power.",
            ],
          },
          {
            subtitle: "3. Grid Connection",
            paragraphs: [
              "The converted AC electricity is then fed into the electrical grid, where it can be utilized to power homes, businesses, and other electrical loads. Any excess electricity generated by the PV system is fed back into the grid, allowing homeowners or businesses to earn credits on their utility bills for the surplus energy provided.",
            ],
          },
          {
            subtitle: "4. Household consume",
            paragraphs: [
              "With the solar energy successfully converted into AC electricity, the electricity generated by the PV system can be directly used to power lights, appliances, and other electronic devices within the home or building.",
            ],
          },
          {
            paragraphs: [
              "The process of grid-connected PV systems can be broken down into the following key steps:",
            ],
          },
        ],
      },
      {
        image: { src: "saveBills.png", width: 1320, height: 1880 },
      },
      {
        sectionHeadline: "How does it save your electricity bills?",
        block: [
          {
            paragraphs: ["You can make savings from solar panels in two ways:"],
          },
          {
            subtitle: "1. Direct electricity savings",
            paragraphs: [
              "The first step in the process involves the conversion of sunlight into direct current (DC) electricity by the solar panels. This is achieved through the use of photovoltaic cells, which directly convert solar radiation into electrical energy.",
            ],
          },
          {
            subtitle: "2. Inversion of Electricity",
            paragraphs: [
              "In addition to direct electricity savings, homeowners with grid-connected PV systems may also be eligible for feed-in tariffs. These tariffs allow homeowners to sell any excess electricity generated by their solar panels back to the grid, providing an additional source of income through surplus electricity production. This financial incentive further enhances the economic benefits of grid-connected PV systems, making them an attractive option for homeowners looking to reduce their electricity costs.",
            ],
          },
          {
            paragraphs: [
              "Grid-connected PV systems offer a sustainable and economically viable method of electricity generation while reducing the reliance on traditional fossil fuel-based power generation. By harnessing solar energy and integrating it with the existing electrical grid infrastructure, these systems contribute to the overall reduction of greenhouse gas emissions and environmental impact.",
              `For more information on grid-connected PV systems and their benefits, feel free <a href="/consult" target="_blank" style="text-decoration: underline;">to reach out to our team</a>`,
            ],
          },
        ],
      },
    ],
  },
];
