import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/app/[locale]/components/common/Footer";
import localFont from "next/font/local";
import Navigation from "@/app/[locale]/components/common/Navigation";
import { LocaleTypes, locales } from "@/app/[locale]/i18n/settings";
import { notFound } from "next/navigation";

const walsheim = localFont({
  src: [
    {
      path: "./fonts/GTWalsheimPro-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-walsheim",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: LocaleTypes };
}) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${walsheim.variable} font-sans`}>
        <div className="flex flex-col justify-center items-center">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
