import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/app/[locale]/components/common/Footer";
import localFont from "next/font/local";
import Navigation from "@/app/[locale]/components/common/Navigation";

// const criteriacf = localFont({
//   src: [
//     {
//       path: "./fonts/criteriacf-demibold.otf",
//       weight: "800",
//       style: "normal",
//     },
//     {
//       path: "./fonts/criteriacf-medium.otf",
//       weight: "600",
//       style: "normal",
//     },
//   ],
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-center items-center">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
