name: web ci

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: copy config
        run: cp -r /home/aesolar/docker/config .
      - name: copy env
        run: cp /home/aesolar/docker/frontend.env .env
      - name: build
        run: echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker-compose build
      - name: up
        run: echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker-compose up -d
      - name: prune
        run: yes | echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker system prune
